# Generated by Django 3.1.5 on 2021-01-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habilidades',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
